mocksRootFolder: mocks
enableMockHttps: false
mainPubKey: pub1.key
mainPrivKey: priv1.key
dedicatedURLmockStatus: /get-mock-info
dedicatedURLhealthcheck: /healthcheck
enableFiberPrometheus: false
dedicatedURLfiberPrometheus: /metrics
